name: 'dhis2: deploy artifact'
description: 'Deploy a build artifact to a GH organization/user.'
inputs:
    github-token:
        description: ''
        required: true
    github-org:
        description: ''
        required: true
        default: 'd2-ci'
    github-user:
        description: ''
        required: false
    build-dir:
        description: ''
        required: true
        default: 'build'
runs:
    using: 'node12'
    main: 'index.js'
